version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "hsergiu"
    reviewers:
      - "hsergiu"
    open-pull-requests-limit: 3