version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    command: mongod --logpath /dev/null 
  reaction-insight:
    build: .
    # image: <your-id>.dkr.ecr.<your-region>.amazonaws.com/reaction-insight:latest
    container_name: reaction-insight
    volumes:
      - .:/home/bot/reaction-insight
      - /home/bot/reaction-insight/node_modules
    command: npm run dev
    depends_on:
      - mongodb
volumes:
  mongodb_data:
